import { defineConfig } from "@pandacss/dev"

export default defineConfig({
  preflight: true,
  include: ["./src/**/*.tsx"],
  outdir: "styled-system",
  conditions: {
    light: "[data-theme=light] &, &.light, .light &",
    dark: "[data-theme=dark] &, &.dark, .dark &",
  },
  theme: {
    extend: {
      breakpoints: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1440px",
      },
      tokens: {
        colors: {
          white: { value: "#FFFFFF" },
          black: { value: "#000000" },
          transparent: { value: "transparent" },
          gray: {
            25: { value: "#FDFDFD" },
            50: { value: "#FAFAFA" },
            100: { value: "#F5F5F5" },
            200: { value: "#E9EAEB" },
            300: { value: "#D5D7DA" },
            400: { value: "#A4A7AE" },
            500: { value: "#717680" },
            600: { value: "#535862" },
            700: { value: "#414651" },
            800: { value: "#252B37" },
            900: { value: "#181D27" },
            950: { value: "#0A0D12" },
          },
          grayDark: {
            25: { value: "#FAFAFA" },
            50: { value: "#F7F7F7" },
            100: { value: "#F0F0F1" },
            200: { value: "#ECECED" },
            300: { value: "#CECFD2" },
            400: { value: "#94979C" },
            500: { value: "#85888E" },
            600: { value: "#61656C" },
            700: { value: "#373A41" },
            800: { value: "#22262F" },
            900: { value: "#13161B" },
            950: { value: "#0C0E12" },
          },
          brand: {
            25: { value: "#FCFCFD" },
            50: { value: "#F9F9FB" },
            100: { value: "#EFF1F5" },
            200: { value: "#DCDFEA" },
            300: { value: "#B9C0D4" },
            400: { value: "#7D89B0" },
            500: { value: "#5D6B98" },
            600: { value: "#4A5578" },
            700: { value: "#404968" },
            800: { value: "#30374F" },
            900: { value: "#111322" },
            950: { value: "#0E101B" },
          },
          error: {
            25: { value: "#FFFBFA" },
            50: { value: "#FEF3F2" },
            100: { value: "#FEE4E2" },
            200: { value: "#FECDCA" },
            300: { value: "#FDA29B" },
            400: { value: "#F97066" },
            500: { value: "#F04438" },
            600: { value: "#D92D20" },
            700: { value: "#B42318" },
            800: { value: "#912018" },
            900: { value: "#7A271A" },
            950: { value: "#55160C" },
          },
          warning: {
            25: { value: "#FFFCF5" },
            50: { value: "#FFFAEB" },
            100: { value: "#FEF0C7" },
            200: { value: "#FEDF89" },
            300: { value: "#FEC84B" },
            400: { value: "#FDB022" },
            500: { value: "#F79009" },
            600: { value: "#DC6803" },
            700: { value: "#B54708" },
            800: { value: "#93370D" },
            900: { value: "#7A2E0E" },
            950: { value: "#4E1D09" },
          },
          success: {
            25: { value: "#F6FEF9" },
            50: { value: "#ECFDF3" },
            100: { value: "#DCFAE6" },
            200: { value: "#ABEFC6" },
            300: { value: "#75E0A7" },
            400: { value: "#47CD89" },
            500: { value: "#17B26A" },
            600: { value: "#079455" },
            700: { value: "#067647" },
            800: { value: "#085D3A" },
            900: { value: "#074D31" },
            950: { value: "#053321" },
          },
          grayBlue: {
            25: { value: "#FCFCFD" },
            50: { value: "#F8F9FC" },
            100: { value: "#EAECF5" },
            200: { value: "#D5D9EB" },
            300: { value: "#B3B8DB" },
            400: { value: "#717BBC" },
            500: { value: "#4E5BA6" },
            600: { value: "#3E4784" },
            700: { value: "#363F72" },
            800: { value: "#293056" },
            900: { value: "#101323" },
            950: { value: "#0D0F1C" },
          },
          grayCool: {
            25: { value: "#FCFCFD" },
            50: { value: "#F9F9FB" },
            100: { value: "#EFF1F5" },
            200: { value: "#DCDFEA" },
            300: { value: "#B9C0D4" },
            400: { value: "#7D89B0" },
            500: { value: "#5D6B98" },
            600: { value: "#4A5578" },
            700: { value: "#404968" },
            800: { value: "#30374F" },
            900: { value: "#111322" },
            950: { value: "#0E101B" },
          },
          moss: {
            25: { value: "#FAFDF7" },
            50: { value: "#F5FBEE" },
            100: { value: "#E6F4D7" },
            200: { value: "#CEEAB0" },
            300: { value: "#ACDC79" },
            400: { value: "#86CB3C" },
            500: { value: "#669F2A" },
            600: { value: "#4F7A21" },
            700: { value: "#3F621A" },
            800: { value: "#335015" },
            900: { value: "#2B4212" },
            950: { value: "#1A280B" },
          },
          greenLight: {
            25: { value: "#FAFEF5" },
            50: { value: "#F3FEE7" },
            100: { value: "#E3FBCC" },
            200: { value: "#D0F8AB" },
            300: { value: "#A6EF67" },
            400: { value: "#85E13A" },
            500: { value: "#66C61C" },
            600: { value: "#4CA30D" },
            700: { value: "#3B7C0F" },
            800: { value: "#326212" },
            900: { value: "#2B5314" },
            950: { value: "#15290A" },
          },
          green: {
            25: { value: "#F6FEF9" },
            50: { value: "#EDFCF2" },
            100: { value: "#D3F8DF" },
            200: { value: "#AAF0C4" },
            300: { value: "#73E2A3" },
            400: { value: "#3CCB7F" },
            500: { value: "#16B364" },
            600: { value: "#099250" },
            700: { value: "#087443" },
            800: { value: "#095C37" },
            900: { value: "#084C2E" },
            950: { value: "#052E1C" },
          },
          teal: {
            25: { value: "#F6FEFC" },
            50: { value: "#F0FDF9" },
            100: { value: "#CCFBEF" },
            200: { value: "#99F6E0" },
            300: { value: "#5FE9D0" },
            400: { value: "#2ED3B7" },
            500: { value: "#15B79E" },
            600: { value: "#0E9384" },
            700: { value: "#107569" },
            800: { value: "#125D56" },
            900: { value: "#134E48" },
            950: { value: "#0A2926" },
          },
          cyan: {
            25: { value: "#F5FEFF" },
            50: { value: "#ECFDFF" },
            100: { value: "#CFF9FE" },
            200: { value: "#A5F0FC" },
            300: { value: "#67E3F9" },
            400: { value: "#22CCEE" },
            500: { value: "#06AED4" },
            600: { value: "#088AB2" },
            700: { value: "#0E7090" },
            800: { value: "#155B75" },
            900: { value: "#164C63" },
            950: { value: "#0D2D3A" },
          },
          blueLight: {
            25: { value: "#F5FBFF" },
            50: { value: "#F0F9FF" },
            100: { value: "#E0F2FE" },
            200: { value: "#B9E6FE" },
            300: { value: "#7CD4FD" },
            400: { value: "#36BFFA" },
            500: { value: "#0BA5EC" },
            600: { value: "#0086C9" },
            700: { value: "#026AA2" },
            800: { value: "#065986" },
            900: { value: "#0B4A6F" },
            950: { value: "#062C41" },
          },
          blue: {
            25: { value: "#F5FAFF" },
            50: { value: "#EFF8FF" },
            100: { value: "#D1E9FF" },
            200: { value: "#B2DDFF" },
            300: { value: "#84CAFF" },
            400: { value: "#53B1FD" },
            500: { value: "#2E90FA" },
            600: { value: "#1570EF" },
            700: { value: "#175CD3" },
            800: { value: "#1849A9" },
            900: { value: "#194185" },
            950: { value: "#102A56" },
          },
          blueDark: {
            25: { value: "#F5F8FF" },
            50: { value: "#EFF4FF" },
            100: { value: "#D1E0FF" },
            200: { value: "#B2CCFF" },
            300: { value: "#84ADFF" },
            400: { value: "#528BFF" },
            500: { value: "#2970FF" },
            600: { value: "#155EEF" },
            700: { value: "#004EEB" },
            800: { value: "#0040C1" },
            900: { value: "#00359E" },
            950: { value: "#002266" },
          },
          indigo: {
            25: { value: "#F5F8FF" },
            50: { value: "#EEF4FF" },
            100: { value: "#E0EAFF" },
            200: { value: "#C7D7FE" },
            300: { value: "#A4BCFD" },
            400: { value: "#8098F9" },
            500: { value: "#6172F3" },
            600: { value: "#444CE7" },
            700: { value: "#3538CD" },
            800: { value: "#2D31A6" },
            900: { value: "#2D3282" },
            950: { value: "#1F235B" },
          },
          violet: {
            25: { value: "#FBFAFF" },
            50: { value: "#F5F3FF" },
            100: { value: "#ECE9FE" },
            200: { value: "#DDD6FE" },
            300: { value: "#C3B5FD" },
            400: { value: "#A48AFB" },
            500: { value: "#875BF7" },
            600: { value: "#7839EE" },
            700: { value: "#6927DA" },
            800: { value: "#5720B7" },
            900: { value: "#491C96" },
            950: { value: "#2E125E" },
          },
          purple: {
            25: { value: "#FAFAFF" },
            50: { value: "#F4F3FF" },
            100: { value: "#EBE9FE" },
            200: { value: "#D9D6FE" },
            300: { value: "#BDB4FE" },
            400: { value: "#9B8AFB" },
            500: { value: "#7A5AF8" },
            600: { value: "#6938EF" },
            700: { value: "#5925DC" },
            800: { value: "#4A1FB8" },
            900: { value: "#3E1C96" },
            950: { value: "#27115F" },
          },
          fuchsia: {
            25: { value: "#FEFAFF" },
            50: { value: "#FDF4FF" },
            100: { value: "#FBE8FF" },
            200: { value: "#F6D0FE" },
            300: { value: "#EEAAFD" },
            400: { value: "#E478FA" },
            500: { value: "#D444F1" },
            600: { value: "#BA24D5" },
            700: { value: "#9F1AB1" },
            800: { value: "#821890" },
            900: { value: "#6F1877" },
            950: { value: "#47104C" },
          },
          pink: {
            25: { value: "#FEF6FB" },
            50: { value: "#FDF2FA" },
            100: { value: "#FCE7F6" },
            200: { value: "#FCCEEE" },
            300: { value: "#FAA7E0" },
            400: { value: "#F670C7" },
            500: { value: "#EE46BC" },
            600: { value: "#DD2590" },
            700: { value: "#C11574" },
            800: { value: "#9E165F" },
            900: { value: "#851651" },
            950: { value: "#4E0D30" },
          },
          rose: {
            25: { value: "#FFF5F6" },
            50: { value: "#FFF1F3" },
            100: { value: "#FFE4E8" },
            200: { value: "#FECDD6" },
            300: { value: "#FEA3B4" },
            400: { value: "#FD6F8E" },
            500: { value: "#F63D68" },
            600: { value: "#E31B54" },
            700: { value: "#C01048" },
            800: { value: "#A11043" },
            900: { value: "#89123E" },
            950: { value: "#510B24" },
          },
          orangeDark: {
            25: { value: "#FFF9F5" },
            50: { value: "#FFF4ED" },
            100: { value: "#FFE6D5" },
            200: { value: "#FFD6AE" },
            300: { value: "#FF9C66" },
            400: { value: "#FF692E" },
            500: { value: "#FF4405" },
            600: { value: "#E62E05" },
            700: { value: "#BC1B06" },
            800: { value: "#97180C" },
            900: { value: "#771A0D" },
            950: { value: "#57130A" },
          },
          orange: {
            25: { value: "#FEFAF5" },
            50: { value: "#FEF6EE" },
            100: { value: "#FDEAD7" },
            200: { value: "#F9DBAF" },
            300: { value: "#F7B27A" },
            400: { value: "#F38744" },
            500: { value: "#EF6820" },
            600: { value: "#E04F16" },
            700: { value: "#B93815" },
            800: { value: "#932F19" },
            900: { value: "#772917" },
            950: { value: "#511C10" },
          },
          yellow: {
            25: { value: "#FEFDF0" },
            50: { value: "#FEFBE8" },
            100: { value: "#FEF7C3" },
            200: { value: "#FEEE95" },
            300: { value: "#FDE272" },
            400: { value: "#FAC515" },
            500: { value: "#EAAA08" },
            600: { value: "#CA8504" },
            700: { value: "#A15C07" },
            800: { value: "#854A0E" },
            900: { value: "#713B12" },
            950: { value: "#542C0D" },
          },
        },
        spacing: {
          none: { value: "0px" },
          xxs: { value: "2px" },
          xs: { value: "4px" },
          sm: { value: "6px" },
          md: { value: "8px" },
          lg: { value: "12px" },
          xl: { value: "16px" },
          "2xl": { value: "20px" },
          "3xl": { value: "24px" },
          "4xl": { value: "32px" },
          "5xl": { value: "40px" },
          "6xl": { value: "48px" },
          "7xl": { value: "64px" },
          "8xl": { value: "80px" },
          "9xl": { value: "96px" },
          "10xl": { value: "128px" },
          "11xl": { value: "160px" },
        },
        radii: {
          none: { value: "0px" },
          xxs: { value: "2px" },
          xs: { value: "4px" },
          sm: { value: "6px" },
          md: { value: "8px" },
          lg: { value: "10px" },
          xl: { value: "12px" },
          "2xl": { value: "16px" },
          "3xl": { value: "20px" },
          "4xl": { value: "24px" },
          full: { value: "9999px" },
        },
        fonts: {
          display: { value: "Inter, sans-serif" },
          body: { value: "Inter, sans-serif" },
        },
        fontSizes: {
          "text-xs": { value: "12px" },
          "text-sm": { value: "14px" },
          "text-md": { value: "16px" },
          "text-lg": { value: "18px" },
          "text-xl": { value: "20px" },
          "display-xs": { value: "24px" },
          "display-sm": { value: "30px" },
          "display-md": { value: "36px" },
          "display-lg": { value: "48px" },
          "display-xl": { value: "60px" },
          "display-2xl": { value: "72px" },
        },
        lineHeights: {
          "text-xs": { value: "18px" },
          "text-sm": { value: "20px" },
          "text-md": { value: "24px" },
          "text-lg": { value: "28px" },
          "text-xl": { value: "30px" },
          "display-xs": { value: "32px" },
          "display-sm": { value: "38px" },
          "display-md": { value: "44px" },
          "display-lg": { value: "60px" },
          "display-xl": { value: "72px" },
          "display-2xl": { value: "90px" },
        },
        fontWeights: {
          regular: { value: "400" },
          medium: { value: "500" },
          semibold: { value: "600" },
          bold: { value: "700" },
        },
        sizes: {
          xxs: { value: "320px" },
          xs: { value: "384px" },
          sm: { value: "480px" },
          md: { value: "560px" },
          lg: { value: "640px" },
          xl: { value: "768px" },
          "2xl": { value: "1024px" },
          "3xl": { value: "1280px" },
          "4xl": { value: "1440px" },
          "5xl": { value: "1600px" },
          "6xl": { value: "1920px" },
          paragraphMaxWidth: { value: "720px" },
        },
      },
      semanticTokens: {
        colors: {
          // ── Text ──────────────────────────────────────────────
          text: {
            primary: {
              value: { _light: "{colors.gray.900}", _dark: "{colors.grayDark.50}" },
            },
            "primary.on-brand": {
              value: { _light: "{colors.white}", _dark: "{colors.grayDark.50}" },
            },
            secondary: {
              value: { _light: "{colors.gray.700}", _dark: "{colors.grayDark.300}" },
            },
            "secondary.hover": {
              value: { _light: "{colors.gray.800}", _dark: "{colors.grayDark.200}" },
            },
            "secondary.on-brand": {
              value: { _light: "{colors.blueDark.200}", _dark: "{colors.grayDark.300}" },
            },
            tertiary: {
              value: { _light: "{colors.gray.600}", _dark: "{colors.grayDark.400}" },
            },
            "tertiary.hover": {
              value: { _light: "{colors.gray.700}", _dark: "{colors.grayDark.300}" },
            },
            "tertiary.on-brand": {
              value: { _light: "{colors.blueDark.200}", _dark: "{colors.grayDark.400}" },
            },
            quaternary: {
              value: { _light: "{colors.gray.500}", _dark: "{colors.grayDark.400}" },
            },
            "quaternary.on-brand": {
              value: { _light: "{colors.blueDark.300}", _dark: "{colors.grayDark.400}" },
            },
            white: {
              value: { _light: "{colors.white}", _dark: "{colors.white}" },
            },
            disabled: {
              value: { _light: "{colors.gray.500}", _dark: "{colors.grayDark.500}" },
            },
            placeholder: {
              value: { _light: "{colors.gray.500}", _dark: "{colors.grayDark.500}" },
            },
            "placeholder.subtle": {
              value: { _light: "{colors.gray.300}", _dark: "{colors.grayDark.700}" },
            },
            "brand.primary": {
              value: { _light: "{colors.blueDark.900}", _dark: "{colors.grayDark.50}" },
            },
            "brand.secondary": {
              value: { _light: "{colors.blueDark.700}", _dark: "{colors.grayDark.300}" },
            },
            "brand.secondary.hover": {
              value: { _light: "{colors.blueDark.800}", _dark: "{colors.grayDark.200}" },
            },
            "brand.tertiary": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.grayDark.400}" },
            },
            "brand.tertiary.alt": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.grayDark.50}" },
            },
            "error.primary": {
              value: { _light: "{colors.error.600}", _dark: "{colors.error.400}" },
            },
            "error.primary.hover": {
              value: { _light: "{colors.error.700}", _dark: "{colors.error.300}" },
            },
            "warning.primary": {
              value: { _light: "{colors.warning.600}", _dark: "{colors.warning.400}" },
            },
            "success.primary": {
              value: { _light: "{colors.success.600}", _dark: "{colors.success.400}" },
            },
          },
          // ── Border ────────────────────────────────────────────
          border: {
            primary: {
              value: { _light: "{colors.gray.300}", _dark: "{colors.grayDark.700}" },
            },
            secondary: {
              value: { _light: "{colors.gray.200}", _dark: "{colors.grayDark.800}" },
            },
            "secondary.alt": {
              value: { _light: "{colors.black}", _dark: "{colors.grayDark.700}" },
            },
            tertiary: {
              value: { _light: "{colors.gray.100}", _dark: "{colors.grayDark.800}" },
            },
            disabled: {
              value: { _light: "{colors.gray.300}", _dark: "{colors.grayDark.700}" },
            },
            "disabled.subtle": {
              value: { _light: "{colors.gray.200}", _dark: "{colors.grayDark.800}" },
            },
            brand: {
              value: { _light: "{colors.blueDark.500}", _dark: "{colors.blueDark.400}" },
            },
            "brand.alt": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.grayDark.700}" },
            },
            error: {
              value: { _light: "{colors.error.500}", _dark: "{colors.error.400}" },
            },
            "error.subtle": {
              value: { _light: "{colors.error.300}", _dark: "{colors.error.500}" },
            },
          },
          // ── Foreground ────────────────────────────────────────
          fg: {
            primary: {
              value: { _light: "{colors.gray.900}", _dark: "{colors.white}" },
            },
            secondary: {
              value: { _light: "{colors.gray.700}", _dark: "{colors.grayDark.300}" },
            },
            "secondary.hover": {
              value: { _light: "{colors.gray.800}", _dark: "{colors.grayDark.200}" },
            },
            tertiary: {
              value: { _light: "{colors.gray.600}", _dark: "{colors.grayDark.400}" },
            },
            "tertiary.hover": {
              value: { _light: "{colors.gray.700}", _dark: "{colors.grayDark.300}" },
            },
            quaternary: {
              value: { _light: "{colors.gray.400}", _dark: "{colors.grayDark.600}" },
            },
            "quaternary.hover": {
              value: { _light: "{colors.gray.500}", _dark: "{colors.grayDark.500}" },
            },
            white: {
              value: { _light: "{colors.white}", _dark: "{colors.white}" },
            },
            disabled: {
              value: { _light: "{colors.gray.400}", _dark: "{colors.grayDark.500}" },
            },
            "disabled.subtle": {
              value: { _light: "{colors.gray.300}", _dark: "{colors.grayDark.600}" },
            },
            "brand.primary": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.blueDark.500}" },
            },
            "brand.primary.alt": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.grayDark.300}" },
            },
            "brand.secondary": {
              value: { _light: "{colors.blueDark.500}", _dark: "{colors.blueDark.500}" },
            },
            "brand.secondary.alt": {
              value: { _light: "{colors.blueDark.500}", _dark: "{colors.grayDark.600}" },
            },
            "brand.secondary.hover": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.grayDark.500}" },
            },
            "error.primary": {
              value: { _light: "{colors.error.600}", _dark: "{colors.error.500}" },
            },
            "error.secondary": {
              value: { _light: "{colors.error.500}", _dark: "{colors.error.400}" },
            },
            "warning.primary": {
              value: { _light: "{colors.warning.600}", _dark: "{colors.warning.500}" },
            },
            "warning.secondary": {
              value: { _light: "{colors.warning.500}", _dark: "{colors.warning.400}" },
            },
            "success.primary": {
              value: { _light: "{colors.success.600}", _dark: "{colors.success.500}" },
            },
            "success.secondary": {
              value: { _light: "{colors.success.500}", _dark: "{colors.success.400}" },
            },
          },
          // ── Background ────────────────────────────────────────
          bg: {
            primary: {
              value: { _light: "{colors.white}", _dark: "{colors.grayDark.950}" },
            },
            "primary.alt": {
              value: { _light: "{colors.white}", _dark: "{colors.grayDark.900}" },
            },
            "primary.hover": {
              value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.800}" },
            },
            "primary.solid": {
              value: { _light: "{colors.gray.950}", _dark: "{colors.grayDark.900}" },
            },
            secondary: {
              value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.900}" },
            },
            "secondary.alt": {
              value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.950}" },
            },
            "secondary.hover": {
              value: { _light: "{colors.gray.100}", _dark: "{colors.grayDark.800}" },
            },
            "secondary.subtle": {
              value: { _light: "{colors.gray.25}", _dark: "{colors.grayDark.900}" },
            },
            "secondary.solid": {
              value: { _light: "{colors.gray.600}", _dark: "{colors.grayDark.600}" },
            },
            tertiary: {
              value: { _light: "{colors.gray.100}", _dark: "{colors.grayDark.800}" },
            },
            quaternary: {
              value: { _light: "{colors.gray.200}", _dark: "{colors.grayDark.700}" },
            },
            active: {
              value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.800}" },
            },
            disabled: {
              value: { _light: "{colors.gray.100}", _dark: "{colors.grayDark.800}" },
            },
            "disabled.subtle": {
              value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.900}" },
            },
            overlay: {
              value: { _light: "{colors.gray.950}", _dark: "{colors.grayDark.800}" },
            },
            "brand.primary": {
              value: { _light: "{colors.blueDark.50}", _dark: "{colors.blueDark.500}" },
            },
            "brand.primary.alt": {
              value: { _light: "{colors.blueDark.50}", _dark: "{colors.grayDark.900}" },
            },
            "brand.secondary": {
              value: { _light: "{colors.blueDark.100}", _dark: "{colors.blueDark.600}" },
            },
            "brand.solid": {
              value: { _light: "{colors.blueDark.600}", _dark: "{colors.blueDark.600}" },
            },
            "brand.solid.hover": {
              value: { _light: "{colors.blueDark.700}", _dark: "{colors.blueDark.500}" },
            },
            "brand.section": {
              value: { _light: "{colors.blueDark.800}", _dark: "{colors.grayDark.900}" },
            },
            "brand.section.subtle": {
              value: { _light: "{colors.blueDark.700}", _dark: "{colors.grayDark.950}" },
            },
            "error.primary": {
              value: { _light: "{colors.error.50}", _dark: "{colors.error.950}" },
            },
            "error.secondary": {
              value: { _light: "{colors.error.100}", _dark: "{colors.error.600}" },
            },
            "error.solid": {
              value: { _light: "{colors.error.600}", _dark: "{colors.error.600}" },
            },
            "warning.primary": {
              value: { _light: "{colors.warning.50}", _dark: "{colors.warning.950}" },
            },
            "warning.secondary": {
              value: { _light: "{colors.warning.100}", _dark: "{colors.warning.600}" },
            },
            "warning.solid": {
              value: { _light: "{colors.warning.600}", _dark: "{colors.warning.600}" },
            },
            "success.primary": {
              value: { _light: "{colors.success.50}", _dark: "{colors.success.950}" },
            },
            "success.secondary": {
              value: { _light: "{colors.success.100}", _dark: "{colors.success.600}" },
            },
            "success.solid": {
              value: { _light: "{colors.success.600}", _dark: "{colors.success.600}" },
            },
          },
          // ── Effects ───────────────────────────────────────────
          effects: {
            "focus-ring": {
              value: { _light: "{colors.blueDark.500}", _dark: "{colors.blueDark.500}" },
            },
            "focus-ring-error": {
              value: { _light: "{colors.error.500}", _dark: "{colors.error.500}" },
            },
          },
          // ── Utility ───────────────────────────────────────────
          utility: {
            gray: {
              50: { value: { _light: "{colors.gray.50}", _dark: "{colors.grayDark.900}" } },
              100: { value: { _light: "{colors.gray.100}", _dark: "{colors.grayDark.800}" } },
              200: { value: { _light: "{colors.gray.200}", _dark: "{colors.grayDark.700}" } },
              300: { value: { _light: "{colors.gray.300}", _dark: "{colors.grayDark.700}" } },
              400: { value: { _light: "{colors.gray.400}", _dark: "{colors.grayDark.600}" } },
              500: { value: { _light: "{colors.gray.500}", _dark: "{colors.grayDark.500}" } },
              600: { value: { _light: "{colors.gray.600}", _dark: "{colors.grayDark.400}" } },
              700: { value: { _light: "{colors.gray.700}", _dark: "{colors.grayDark.300}" } },
              800: { value: { _light: "{colors.gray.800}", _dark: "{colors.grayDark.200}" } },
              900: { value: { _light: "{colors.gray.900}", _dark: "{colors.grayDark.100}" } },
            },
            brand: {
              50: { value: { _light: "{colors.blueDark.50}", _dark: "{colors.blueDark.950}" } },
              100: { value: { _light: "{colors.blueDark.100}", _dark: "{colors.blueDark.900}" } },
              200: { value: { _light: "{colors.blueDark.200}", _dark: "{colors.blueDark.800}" } },
              300: { value: { _light: "{colors.blueDark.300}", _dark: "{colors.blueDark.700}" } },
              400: { value: { _light: "{colors.blueDark.400}", _dark: "{colors.blueDark.600}" } },
              500: { value: { _light: "{colors.blueDark.500}", _dark: "{colors.blueDark.500}" } },
              600: { value: { _light: "{colors.blueDark.600}", _dark: "{colors.blueDark.400}" } },
              700: { value: { _light: "{colors.blueDark.700}", _dark: "{colors.blueDark.300}" } },
              800: { value: { _light: "{colors.blueDark.800}", _dark: "{colors.blueDark.200}" } },
              900: { value: { _light: "{colors.blueDark.900}", _dark: "{colors.blueDark.100}" } },
            },
            error: {
              50: { value: { _light: "{colors.error.50}", _dark: "{colors.error.950}" } },
              100: { value: { _light: "{colors.error.100}", _dark: "{colors.error.900}" } },
              200: { value: { _light: "{colors.error.200}", _dark: "{colors.error.800}" } },
              300: { value: { _light: "{colors.error.300}", _dark: "{colors.error.700}" } },
              400: { value: { _light: "{colors.error.400}", _dark: "{colors.error.600}" } },
              500: { value: { _light: "{colors.error.500}", _dark: "{colors.error.500}" } },
              600: { value: { _light: "{colors.error.600}", _dark: "{colors.error.400}" } },
              700: { value: { _light: "{colors.error.700}", _dark: "{colors.error.300}" } },
            },
            warning: {
              50: { value: { _light: "{colors.warning.50}", _dark: "{colors.warning.950}" } },
              100: { value: { _light: "{colors.warning.100}", _dark: "{colors.warning.900}" } },
              200: { value: { _light: "{colors.warning.200}", _dark: "{colors.warning.800}" } },
              300: { value: { _light: "{colors.warning.300}", _dark: "{colors.warning.700}" } },
              400: { value: { _light: "{colors.warning.400}", _dark: "{colors.warning.600}" } },
              500: { value: { _light: "{colors.warning.500}", _dark: "{colors.warning.500}" } },
              600: { value: { _light: "{colors.warning.600}", _dark: "{colors.warning.400}" } },
              700: { value: { _light: "{colors.warning.700}", _dark: "{colors.warning.300}" } },
            },
            success: {
              50: { value: { _light: "{colors.success.50}", _dark: "{colors.success.950}" } },
              100: { value: { _light: "{colors.success.100}", _dark: "{colors.success.900}" } },
              200: { value: { _light: "{colors.success.200}", _dark: "{colors.success.800}" } },
              300: { value: { _light: "{colors.success.300}", _dark: "{colors.success.700}" } },
              400: { value: { _light: "{colors.success.400}", _dark: "{colors.success.600}" } },
              500: { value: { _light: "{colors.success.500}", _dark: "{colors.success.500}" } },
              600: { value: { _light: "{colors.success.600}", _dark: "{colors.success.400}" } },
              700: { value: { _light: "{colors.success.700}", _dark: "{colors.success.300}" } },
            },
            grayBlue: {
              50: { value: { _light: "{colors.grayBlue.50}", _dark: "{colors.grayBlue.950}" } },
              100: { value: { _light: "{colors.grayBlue.100}", _dark: "{colors.grayBlue.900}" } },
              200: { value: { _light: "{colors.grayBlue.200}", _dark: "{colors.grayBlue.800}" } },
              300: { value: { _light: "{colors.grayBlue.300}", _dark: "{colors.grayBlue.700}" } },
              400: { value: { _light: "{colors.grayBlue.400}", _dark: "{colors.grayBlue.600}" } },
              500: { value: { _light: "{colors.grayBlue.500}", _dark: "{colors.grayBlue.500}" } },
              600: { value: { _light: "{colors.grayBlue.600}", _dark: "{colors.grayBlue.400}" } },
              700: { value: { _light: "{colors.grayBlue.700}", _dark: "{colors.grayBlue.300}" } },
            },
            green: {
              50: { value: { _light: "{colors.green.50}", _dark: "{colors.green.950}" } },
              100: { value: { _light: "{colors.green.100}", _dark: "{colors.green.900}" } },
              200: { value: { _light: "{colors.green.200}", _dark: "{colors.green.800}" } },
              300: { value: { _light: "{colors.green.300}", _dark: "{colors.green.700}" } },
              400: { value: { _light: "{colors.green.400}", _dark: "{colors.green.600}" } },
              500: { value: { _light: "{colors.green.500}", _dark: "{colors.green.500}" } },
              600: { value: { _light: "{colors.green.600}", _dark: "{colors.green.400}" } },
              700: { value: { _light: "{colors.green.700}", _dark: "{colors.green.300}" } },
            },
            blueLight: {
              50: { value: { _light: "{colors.blueLight.50}", _dark: "{colors.blueLight.950}" } },
              100: { value: { _light: "{colors.blueLight.100}", _dark: "{colors.blueLight.900}" } },
              200: { value: { _light: "{colors.blueLight.200}", _dark: "{colors.blueLight.800}" } },
              300: { value: { _light: "{colors.blueLight.300}", _dark: "{colors.blueLight.700}" } },
              400: { value: { _light: "{colors.blueLight.400}", _dark: "{colors.blueLight.600}" } },
              500: { value: { _light: "{colors.blueLight.500}", _dark: "{colors.blueLight.500}" } },
              600: { value: { _light: "{colors.blueLight.600}", _dark: "{colors.blueLight.400}" } },
              700: { value: { _light: "{colors.blueLight.700}", _dark: "{colors.blueLight.300}" } },
            },
            blue: {
              50: { value: { _light: "{colors.blue.50}", _dark: "{colors.blue.950}" } },
              100: { value: { _light: "{colors.blue.100}", _dark: "{colors.blue.900}" } },
              200: { value: { _light: "{colors.blue.200}", _dark: "{colors.blue.800}" } },
              300: { value: { _light: "{colors.blue.300}", _dark: "{colors.blue.700}" } },
              400: { value: { _light: "{colors.blue.400}", _dark: "{colors.blue.600}" } },
              500: { value: { _light: "{colors.blue.500}", _dark: "{colors.blue.500}" } },
              600: { value: { _light: "{colors.blue.600}", _dark: "{colors.blue.400}" } },
              700: { value: { _light: "{colors.blue.700}", _dark: "{colors.blue.300}" } },
            },
            blueDark: {
              50: { value: { _light: "{colors.blueDark.50}", _dark: "{colors.blueDark.950}" } },
              100: { value: { _light: "{colors.blueDark.100}", _dark: "{colors.blueDark.900}" } },
              200: { value: { _light: "{colors.blueDark.200}", _dark: "{colors.blueDark.800}" } },
              300: { value: { _light: "{colors.blueDark.300}", _dark: "{colors.blueDark.700}" } },
              400: { value: { _light: "{colors.blueDark.400}", _dark: "{colors.blueDark.600}" } },
              500: { value: { _light: "{colors.blueDark.500}", _dark: "{colors.blueDark.500}" } },
              600: { value: { _light: "{colors.blueDark.600}", _dark: "{colors.blueDark.400}" } },
              700: { value: { _light: "{colors.blueDark.700}", _dark: "{colors.blueDark.300}" } },
            },
            indigo: {
              50: { value: { _light: "{colors.indigo.50}", _dark: "{colors.indigo.950}" } },
              100: { value: { _light: "{colors.indigo.100}", _dark: "{colors.indigo.900}" } },
              200: { value: { _light: "{colors.indigo.200}", _dark: "{colors.indigo.800}" } },
              300: { value: { _light: "{colors.indigo.300}", _dark: "{colors.indigo.700}" } },
              400: { value: { _light: "{colors.indigo.400}", _dark: "{colors.indigo.600}" } },
              500: { value: { _light: "{colors.indigo.500}", _dark: "{colors.indigo.500}" } },
              600: { value: { _light: "{colors.indigo.600}", _dark: "{colors.indigo.400}" } },
              700: { value: { _light: "{colors.indigo.700}", _dark: "{colors.indigo.300}" } },
            },
            purple: {
              50: { value: { _light: "{colors.purple.50}", _dark: "{colors.purple.950}" } },
              100: { value: { _light: "{colors.purple.100}", _dark: "{colors.purple.900}" } },
              200: { value: { _light: "{colors.purple.200}", _dark: "{colors.purple.800}" } },
              300: { value: { _light: "{colors.purple.300}", _dark: "{colors.purple.700}" } },
              400: { value: { _light: "{colors.purple.400}", _dark: "{colors.purple.600}" } },
              500: { value: { _light: "{colors.purple.500}", _dark: "{colors.purple.500}" } },
              600: { value: { _light: "{colors.purple.600}", _dark: "{colors.purple.400}" } },
              700: { value: { _light: "{colors.purple.700}", _dark: "{colors.purple.300}" } },
            },
            fuchsia: {
              50: { value: { _light: "{colors.fuchsia.50}", _dark: "{colors.fuchsia.950}" } },
              100: { value: { _light: "{colors.fuchsia.100}", _dark: "{colors.fuchsia.900}" } },
              200: { value: { _light: "{colors.fuchsia.200}", _dark: "{colors.fuchsia.800}" } },
              300: { value: { _light: "{colors.fuchsia.300}", _dark: "{colors.fuchsia.700}" } },
              400: { value: { _light: "{colors.fuchsia.400}", _dark: "{colors.fuchsia.600}" } },
              500: { value: { _light: "{colors.fuchsia.500}", _dark: "{colors.fuchsia.500}" } },
              600: { value: { _light: "{colors.fuchsia.600}", _dark: "{colors.fuchsia.400}" } },
              700: { value: { _light: "{colors.fuchsia.700}", _dark: "{colors.fuchsia.300}" } },
            },
            pink: {
              50: { value: { _light: "{colors.pink.50}", _dark: "{colors.pink.950}" } },
              100: { value: { _light: "{colors.pink.100}", _dark: "{colors.pink.900}" } },
              200: { value: { _light: "{colors.pink.200}", _dark: "{colors.pink.800}" } },
              300: { value: { _light: "{colors.pink.300}", _dark: "{colors.pink.700}" } },
              400: { value: { _light: "{colors.pink.400}", _dark: "{colors.pink.600}" } },
              500: { value: { _light: "{colors.pink.500}", _dark: "{colors.pink.500}" } },
              600: { value: { _light: "{colors.pink.600}", _dark: "{colors.pink.400}" } },
              700: { value: { _light: "{colors.pink.700}", _dark: "{colors.pink.300}" } },
            },
            orangeDark: {
              50: { value: { _light: "{colors.orangeDark.50}", _dark: "{colors.orangeDark.950}" } },
              100: { value: { _light: "{colors.orangeDark.100}", _dark: "{colors.orangeDark.900}" } },
              200: { value: { _light: "{colors.orangeDark.200}", _dark: "{colors.orangeDark.800}" } },
              300: { value: { _light: "{colors.orangeDark.300}", _dark: "{colors.orangeDark.700}" } },
              400: { value: { _light: "{colors.orangeDark.400}", _dark: "{colors.orangeDark.600}" } },
              500: { value: { _light: "{colors.orangeDark.500}", _dark: "{colors.orangeDark.500}" } },
              600: { value: { _light: "{colors.orangeDark.600}", _dark: "{colors.orangeDark.400}" } },
              700: { value: { _light: "{colors.orangeDark.700}", _dark: "{colors.orangeDark.300}" } },
            },
            orange: {
              50: { value: { _light: "{colors.orange.50}", _dark: "{colors.orange.950}" } },
              100: { value: { _light: "{colors.orange.100}", _dark: "{colors.orange.900}" } },
              200: { value: { _light: "{colors.orange.200}", _dark: "{colors.orange.800}" } },
              300: { value: { _light: "{colors.orange.300}", _dark: "{colors.orange.700}" } },
              400: { value: { _light: "{colors.orange.400}", _dark: "{colors.orange.600}" } },
              500: { value: { _light: "{colors.orange.500}", _dark: "{colors.orange.500}" } },
              600: { value: { _light: "{colors.orange.600}", _dark: "{colors.orange.400}" } },
              700: { value: { _light: "{colors.orange.700}", _dark: "{colors.orange.300}" } },
            },
            yellow: {
              50: { value: { _light: "{colors.yellow.50}", _dark: "{colors.yellow.950}" } },
              100: { value: { _light: "{colors.yellow.100}", _dark: "{colors.yellow.900}" } },
              200: { value: { _light: "{colors.yellow.200}", _dark: "{colors.yellow.800}" } },
              300: { value: { _light: "{colors.yellow.300}", _dark: "{colors.yellow.700}" } },
              400: { value: { _light: "{colors.yellow.400}", _dark: "{colors.yellow.600}" } },
              500: { value: { _light: "{colors.yellow.500}", _dark: "{colors.yellow.500}" } },
              600: { value: { _light: "{colors.yellow.600}", _dark: "{colors.yellow.400}" } },
              700: { value: { _light: "{colors.yellow.700}", _dark: "{colors.yellow.300}" } },
            },
          },
        },
      },
    },
  },
})
