/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HarnessRouteImport } from './routes/harness'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsArchivedRouteImport } from './routes/projects/archived'

const HarnessRoute = HarnessRouteImport.update({
  id: '/harness',
  path: '/harness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsArchivedRoute = ProjectsArchivedRouteImport.update({
  id: '/projects/archived',
  path: '/projects/archived',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harness': typeof HarnessRoute
  '/projects/archived': typeof ProjectsArchivedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harness': typeof HarnessRoute
  '/projects/archived': typeof ProjectsArchivedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harness': typeof HarnessRoute
  '/projects/archived': typeof ProjectsArchivedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harness' | '/projects/archived'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harness' | '/projects/archived'
  id: '__root__' | '/' | '/harness' | '/projects/archived'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarnessRoute: typeof HarnessRoute
  ProjectsArchivedRoute: typeof ProjectsArchivedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/harness': {
      id: '/harness'
      path: '/harness'
      fullPath: '/harness'
      preLoaderRoute: typeof HarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/archived': {
      id: '/projects/archived'
      path: '/projects/archived'
      fullPath: '/projects/archived'
      preLoaderRoute: typeof ProjectsArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarnessRoute: HarnessRoute,
  ProjectsArchivedRoute: ProjectsArchivedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
